"""initial

Revision ID: 1c50833911b9
Revises: 662b74e1f2df
Create Date: 2026-08-24 00:25:43.915786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c50833911b9'
down_revision: Union[str, None] = '662b74e1f2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_verification_tokens_token_hash_key', 'email_verification_tokens', type_='unique')
    op.drop_constraint('mfa_backup_codes_code_hash_key', 'mfa_backup_codes', type_='unique')
    op.drop_constraint('mfa_challenges_token_hash_key', 'mfa_challenges', type_='unique')
    op.drop_constraint('password_reset_tokens_token_hash_key', 'password_reset_tokens', type_='unique')
    op.drop_constraint('user_sessions_refresh_token_hash_key', 'user_sessions', type_='unique')
    op.drop_constraint('user_sessions_session_token_hash_key', 'user_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_sessions_session_token_hash_key', 'user_sessions', ['session_token_hash'])
    op.create_unique_constraint('user_sessions_refresh_token_hash_key', 'user_sessions', ['refresh_token_hash'])
    op.create_unique_constraint('password_reset_tokens_token_hash_key', 'password_reset_tokens', ['token_hash'])
    op.create_unique_constraint('mfa_challenges_token_hash_key', 'mfa_challenges', ['token_hash'])
    op.create_unique_constraint('mfa_backup_codes_code_hash_key', 'mfa_backup_codes', ['code_hash'])
    op.create_unique_constraint('email_verification_tokens_token_hash_key', 'email_verification_tokens', ['token_hash'])
    # ### end Alembic commands ###
